//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net_MVC_Otopark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Arac
    {
        public int AracID { get; set; }
        public string AracPlakası { get; set; }
        public Nullable<System.DateTime> AracGirisTarihi { get; set; }
        public Nullable<bool> AracAktiflik { get; set; }
        public Nullable<System.DateTime> AracCikisTarihi { get; set; }
    }
}
